# Generated by Django 5.1 on 2024-08-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DateField()),
                ('classroom', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField(blank=True, unique=True)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
