# Generated by Django 5.1 on 2024-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DateField()),
                ('classroom', models.CharField(choices=[('Tle', 'Terminale'), ('1ere', 'Première'), ('2nde', 'Deuxième'), ('3eme', 'Troisième'), ('4eme', 'Quatrième'), ('5eme', 'Cinquième'), ('6eme', 'Sixième')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='Homme', max_length=10)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
