# Generated by Django 5.1 on 2024-08-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('is_vacant', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField(blank=True, unique=True)),
                ('subject_taught', models.CharField(max_length=50)),
                ('next_class', models.DateField()),
                ('next_meeting_topic', models.CharField(max_length=100)),
            ],
        ),
    ]
