# Generated by Django 5.1 on 2024-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_next_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('is_vacant', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField(blank=True, unique=True)),
                ('subject_taught', models.CharField(choices=[('math', 'Math'), ('physique', 'Physique'), ('anglais', 'Anglais'), ('svt', 'SVT'), ('histoire', 'Histoire'), ('français', 'Français')], max_length=20)),
                ('next_class', models.CharField(max_length=50)),
                ('next_meeting_topic', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
