# Generated by Django 5.1 on 2024-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teachermodel_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='is_vacant',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20),
        ),
    ]
